### PR TITLE
Updated package name

### PR DESCRIPTION
**Pull request by BurnhamR**
WARNING !
This will break all current forks and pull requests! 

You must sync your repo before making any future pull requests!

### CODE REVIEW

**Comment by JustDesoroxxx** [comment]
Huh this will probably create a shit ton of mod incompatibility

**Comment by JustDesoroxxx** [comment]
Any mod you try to detect if the main class is here will not find it and throw a class not found exception, this might be harmless for some mods.
Or can break the compat they add.
Worst case scenario it's gonna corrupt world. 

My biggest concern with this is break any add-on that exists

**Comment by Paneedah** [comment]
It should be fine, Ive tested it in 3 small-medium sized modpacks that use Vic's and it seems to not have impacted anything and still works.

Worst case scenario, this may need to be reverted in case there is any weird add-ons that have funny interactions with VMW, I do advise for developers to use the official method for detecting the mod though as detecting the main class directly isn't the best way to do it at all.

**Comment by JustDesoroxxx** [comment]
Detecting with the official way is not possible for some mods.

But actually now that I am thinking about it if a mods needs it we can just add an empty class either the main class name with the same package as the old one

**Comment by Paneedah** [comment]
Yeah we could just do that as well.

**Pull request merged**
